name: Build Executable

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas simpledbf PyPDF2

    - name: Verify Python installation
      run: |
        python --version
        pip --version

    - name: Build executable
      run: |
        pyinstaller --onefile extract_pdf_info.py
      shell: bash

    - name: Debug build
      run: |
        echo "PyInstaller build step finished with code $?"
        if [ $? -ne 0 ]; then
          echo "PyInstaller build failed"
          cat dist/*  # Print the content of dist directory if it exists
          cat build/*  # Print the content of build directory if it exists
          exit 1
        fi
      shell: bash

    - name: List files for debug
      run: |
        echo "Listing contents of dist and build directories"
        ls -alh dist/ || echo "No dist directory found"
        ls -alh build/ || echo "No build directory found"

    - name: Upload executable
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: dist/extract_pdf_info*
